--- # Setup LogDNA on Amazon Linux 2 Instance
- name:  "Import the RPM LogDNA GPG Key"
  rpm_key:
    state: present
    key:   https://repo.logdna.com/logdna.gpg

- name:    "Configure the LogDNA Repo"
  copy:
    src:   ../files/logdna.repo
    dest:  /etc/yum.repos.d/
    owner: root
    group: root
    mode:  "0644"

- name:    "Install the LogDNA Agent"
  yum:
    name:  logdna-agent
    state: latest

- name: "Setup LogDNA log ingestion"
  copy:
    src:   ../files/logdna.conf
    dest:  /etc/
    owner: root
    group: root
    mode:  "0644"

- name:  "Configure the LogDNA Agent"
  shell: logdna-agent -k {{ logdna_key }}

- name: "Enable the LogDNA Agent"
  shell: |
    systemctl enable logdna-agent
    systemctl restart logdna-agent
