---
- name: "Update all packages to latest version"
  yum:
    name: "*"
    state: latest

- name: "Install specific package set for MUD development"
  yum:
    name:
      - jq
      - telnet
      - gdb
      - git
      - gcc
    state: latest

- name: "[shell] Enable amazon-linux-extras packages"
  shell: amazon-linux-extras enable docker

- name: "Install docker via package manager"
  yum:
    name: docker
    state: latest

- name: "[shell] Configure docker startup"
  shell: systemctl enable docker

- name: "[shell] Configure user-group docker management"
  shell: usermod -aG docker ec2-user

- name: "Start docker service if not started"
  service:
    name: docker
    state: started

- name: "Setup .bashrc for ec2-user."
  copy:
    src:   ../files/.bashrc
    dest:  /home/ec2-user/
    owner: ec2-user
    group: ec2-user
    mode: "0644"

- name: "Setup .gitconfig for ec2-user."
  copy:
    src:   ~/.outside_files/.gitconfig
    dest:  /home/ec2-user/
    owner: ec2-user
    group: ec2-user
    mode:  "0644"
